### ISSUE TITLE
Unity integration

### ISSUE THREAD

**Issue by bogusindustries** [pozil/salesforce-unity-sdk#2] opened 2019-07-11 21:14 UTC
To start, I'm very new to programming so I may just be missing something a smarter person wouldn't.

I have followed the instructions to the best of my ability and get the following errors out of Unity:

Salesforce HTTP request: POST 400 https://login.salesforce.com/services/oauth2/token
UnityEngine.Debug:LogError(Object)

Generic/unknown HTTP error
UnityEngine.Debug:LogError(Object)

{"error":"invalid_grant","error_description":"authentication failure"}
UnityEngine.Debug:LogError(Object)

SalesforceAuthenticationException: Salesforce authentication error due to invalid user credentials: authentication failure
Salesforce.SalesforceClient+<login>c__Iterator0.MoveNext () (at Assets/Salesforce/src/sfdc-client/SalesforceClient.cs:84)
Coroutine`1+<internalRoutine>c__Iterator0[System.Boolean].MoveNext () (at Assets/Salesforce/src/util/CoroutineExtensions.cs:42)

If I remove the Test Salesforce Client script component I no longer get errors leading me to believe it has something to do with my credentials, however, I have been signed into the Salesforce Developer edition with the same credentials while running the app in Unity. It says "....all Salesforce Client operations require that you log in to Salesforce beforehand." in the instructions.

Does that mean I need to be signed into a Salesforce account that isn't a developer account?

Our goal is to develop an app where the user customizes a product and sends those specs and other info to a Salesforce account owned by another business (not the business where I work). Am I even in the right place?

**Comment by pozil** [comment] 2019-07-12 08:16
Hi,

This client typically connects to a single Salesforce org but you could create some code that uses multiple clients (one per org) provided that you have the right credentials.

This error you shared indicates that your credentials are not valid.
The problem is likely in the Salesforce client configuration.
You'll need to check your Salesforce credentials:
- connected app's consumer key, consumer secret
- user's username and password.

Also, depending on the type of Salesforce Org you're using, the OAuth endpoint URL is different.
On a production or DE org, the endpoint starts with `https://login.salesforce.com` but on a sandbox or a scratch org it starts with`https://test.salesforce.com` so may need to change that.

I hope that this helps.

**Comment by bogusindustries** [comment] 2019-07-12 16:05
Thank you so much for your help!
I quadruple checked my login, password, consumer key, and consumer secret and believe they are correct.
I changed the default OAuth endpoint from its default (https://login.salesforce.com/services/oauth2/token)
and tried both of your suggestions and the login credentials error no longer happens when either (login or test) are used. Progress!

I, however, get 2 new errors:
Invalid json string, expecting { at 2 UnityEngine.Debug.LogError(Object)
and:
NullReferenceException: Object reference not set to an instance of an object
Salesforce.SalesforceClient+<login>c__Iterator0.MoveNext () (at Assets/Salesforce/src/sfdc-client/SalesforceClient.cs:98)
Coroutine`1+<internalRoutine>c__Iterator0[System.Boolean].MoveNext () (at Assets/Salesforce/src/util/CoroutineExtensions.cs:42)

we have printed out the return of the JSON string which is gigantic so I won't paste it here. 
we have added a bit of code to see what it did find in place of "{" and is returns "<"

We are very new to this so very much appreciate your help.

**Comment by pozil** [comment] 2019-07-19 18:28
My guess is that the request your are trying is returning an HTTP error.
What is the API call or query that you are trying to run?
I need more details in order to help.

**Comment by bogusindustries** [comment] 2019-07-19 19:13
Thanks for your reply!
I guess we're so inexperienced I'm not really sure which API call we would want to run.
The ultimate goal is to have a user build a custom window and when they are happy they send what type of window along with some contact information to a company that builds custom windows' salesforce account. I wanted to see if we could implement that functionality to a dummy account before implementing it to our client's (the window fabricator)  salesforce account. We have the window building part under control, it's the sending information to their salesforce account that we have no idea how to do. 

Maybe there are some learning resources I should look into before even getting this far, but I'm not a programmer and haven't been able to convince my employer to hire someone that actually does this.

Thanks again for your help.

**Comment by pozil** [comment] 2019-07-22 19:07
Sure, no worries but what you are describing is not something a beginner can achieve.
In fact, before working on a Salesforce integration with Unity I suggest that you learn Salesforce development on the Platform first. Check out [Trailhead](https://trailhead.salesforce.com/) our free e-learning platform as a start. You'll find guided paths for developer beginners.

**Comment by bogusindustries** [comment] 2019-07-22 19:27
Awesome!
I'll take a look at that learning path and let you know if I have any questions after that.
Thanks!

**Comment by pozil** [comment] 2019-07-22 20:24
Cool, I am closing this issue for now then. Happy learning.

**Closed as completed by pozil** 2019-07-22 20:24 UTC
